before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - cd mission-uncuttable/code/
  - pip3 install wheel
  - pip3 install -r requirements.txt

test:
  script:
  - pytest

production:
  type: deploy
  script:
  - apt-get install ruby ruby-dev rubygems build-essential
  - gem install --no-ri --no-rdoc fpm
  - fbs freeze
  - fbs installer
