before_script:
  - alias pip="pip3"
  - apk add --update --no-cache python3-dev
  - python3 -m ensurepip
  - rm -r /usr/lib/python*/ensurepip
  - pip3 install --upgrade pip setuptools
  - ls
  - cd code/
  - apk add py3-qt5
  - pip3 install wheel
  - pip3 install -r production.txt

test:
  script:
  - pytest

production:
  type: deploy
  script:
  - fbs freeze
  - fbs installer
