before_script:
  - apk add --update --no-cache python3-dev
  - python3 -m ensurepip
  - rm -r /usr/lib/python*/ensurepip
  - pip3 install --upgrade pip setuptools
  - cd mission-uncuttable/code/
  - pip3 install wheel
  - pip3 install -r requirements.txt

test:
  script:
  - pytest

production:
  type: deploy
  script:
  - apk add ruby ruby-dev rubygems build-essential
  - gem install --no-ri --no-rdoc fpm
  - fbs freeze
  - fbs installer
