before_script:
  - alias pip="pip3"
  - apk add --update --no-cache python3-dev
  - python3 -m ensurepip
  - rm -r /usr/lib/python*/ensurepip
  - pip3 install --upgrade pip setuptools
  - ls
  - cd code/
  - apk add py3-qt5
  - pip3 install wheel
  - pip3 install -r production.txt

test:
  stage: test
  tags:
    - docker-in-docker
  script:
  - pytest

production:
  type: deploy
  tags:
    - docker-in-docker
  script:
  - ln -s /lib/libc.musl-x86_64.so.1 ldd
  - ln -s /lib /lib64  
  - pip3 install PyQt5-sip
  - python configure.py --sip-module PyQt5.sip --no-tools
  - fbs freeze
  - fbs installer
